---
- name:
  unarchive:
    src: "{{ url }}"
    dest: /opt
    remote_src: yes
    creates: "{{ simbol_link_source }}"

- name: crear enlace simbolico tomcat
  file:
    src: "{{ simbol_link_source }}"
    dest: /opt/tomcat
    state: link

- name: modificar fichero catalina
  lineinfile:
    dest: /opt/tomcat/bin/catalina.sh
    regexp: '^(.*){{ search }}(.*)$'
    line: "JAVA_OPTS=\"$JAVA_OPTS -Djava.protocol.handler.pkgs=org.apache.catalina.webresources -Xms{{ tomcat_memory_min }}m -Xmx{{ tomcat_memory_max }}m\""
  notify: tomcat restart

- name: añadir template modificado jj
  template:
    src: templates/tomcat
    dest: /etc/systemd/system/tomcat.service
    mode: 0755

- name: start service
  systemd:
    name: "{{ web_service }}"
    state: started
    enabled: true

